name: Bot Status Check

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Checkout
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Clone the Repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPO_NAME }}
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install python-decouple pytz telethon cryptg
      - name: Run the UserClient
        run: |
          python3 main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOTS: ${{ secrets.BOTS }}
          HOSTS: ${{ secrets.HOSTS }}
          SESSION: ${{ secrets.SESSION }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
